enum ErrorCode {
    RESOURCE_NOT_FOUND = "NOT_FOUND_1001",
    USER_NOT_FOUND = "NOT_FOUND_1002",
    UNAUTHENTICATED = "AUTH_2001",
    SESSION_EXPIRED = "AUTH_2002",
    INVALID_CREDENTIALS = "AUTH_2003",
    UNAUTHORIZED = "AUTHZ_3001",
    REQUIRED_FIELDS = "VALIDATION_4001",
    INVALID_FORMAT = "VALIDATION_4002",
    DUPLICATE_ENTRY = "VALIDATION_4003",
    INTERNAL_ERROR = "INTERNAL_5001",
    DATABASE_ERROR = "INTERNAL_5002",
    EXTERNAL_SERVICE_ERROR = "INTERNAL_5003",
    INVALID_ROUTE = "INTERNAL_5005",
}

export default ErrorCode;